ALTER TABLE "Settings" 
ADD COLUMN IF NOT EXISTS "shippingFeeInsideDhaka" DOUBLE PRECISION NOT NULL DEFAULT 70,
ADD COLUMN IF NOT EXISTS "shippingFeeOutsideDhaka" DOUBLE PRECISION NOT NULL DEFAULT 130,
ADD COLUMN IF NOT EXISTS "freeShippingThreshold" DOUBLE PRECISION NOT NULL DEFAULT 5000,
ADD COLUMN IF NOT EXISTS "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "contactEmail" TEXT NOT NULL DEFAULT 'contact@bdneeds.com',
ADD COLUMN IF NOT EXISTS "contactPhone" TEXT NOT NULL DEFAULT '01811277828';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "isFraud" BOOLEAN NOT NULL DEFAULT false;
