import { Category, Product, Banner, Coupon, Order, Review, User } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-electronics',
    name: 'Electronics & Audio',
    slug: 'electronics',
    description: 'Next-generation acoustic engineering, flagships, and computing essentials.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    icon: 'Headphones',
    productCount: 8,
    isActive: true,
    isFeatured: true,
    order: 1,
  },
  {
    id: 'cat-fashion',
    name: 'Luxury & Apparel',
    slug: 'fashion',
    description: 'Contemporary tailoring, refined silhouettes, and organic premium fabrics.',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80',
    icon: 'Shirt',
    productCount: 6,
    isActive: true,
    isFeatured: true,
    order: 2,
  },
  {
    id: 'cat-footwear',
    name: 'Footwear & Sneakers',
    slug: 'footwear',
    description: 'Ergonomic performance soles, handcrafted leather oxfords, and street classics.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    icon: 'Footprints',
    productCount: 5,
    isActive: true,
    isFeatured: true,
    order: 3,
  },
  {
    id: 'cat-accessories',
    name: 'Watches & Accessories',
    slug: 'accessories',
    description: 'Swiss-inspired horology, minimalist leather goods, and timeless accents.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    icon: 'Watch',
    productCount: 6,
    isActive: true,
    isFeatured: true,
    order: 4,
  },
  {
    id: 'cat-gaming',
    name: 'Gaming & Workstation',
    slug: 'gaming',
    description: 'Ultra-low latency mechanical peripherals, tactile switches, and pro gear.',
    image: 'https://images.unsplash.com/photo-1612287233207-640a2a4b868e?w=800&q=80',
    icon: 'Gamepad2',
    productCount: 5,
    isActive: true,
    isFeatured: true,
    order: 5,
  },
  {
    id: 'cat-home',
    name: 'Smart Living & Climate',
    slug: 'home-appliances',
    description: 'Whisper-quiet air circulators, ambient illumination, and automated appliances.',
    image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&q=80',
    icon: 'Wind',
    productCount: 4,
    isActive: true,
    isFeatured: true,
    order: 6,
  },
  {
    id: 'cat-beauty',
    name: 'Grooming & Skincare',
    slug: 'beauty',
    description: 'Botanical clinical formulations, precision grooming tools, and luxury scents.',
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80',
    icon: 'Sparkles',
    productCount: 4,
    isActive: true,
    isFeatured: true,
    order: 7,
  },
  {
    id: 'cat-smart-devices',
    name: 'Smart Devices & IoT',
    slug: 'smart-devices',
    description: 'Connected speakers, high-fidelity microphones, and intelligent ecosystem hubs.',
    image: 'https://images.unsplash.com/photo-1543512214-318c7553f230?w=800&q=80',
    icon: 'Cpu',
    productCount: 4,
    isActive: true,
    isFeatured: true,
    order: 8,
  },
];

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'banner-1',
    title: 'Acoustic Precision Reimagined',
    subtitle: 'Nova Pro Wireless Studio Series',
    badge: 'NEW FLAGSHIP RELEASE',
    description: 'Custom 40mm titanium biocellulose drivers with adaptive ANC and 50-hour battery life.',
    price: 349,
    discount: 50,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1600&q=85',
    ctaText: 'Explore Nova Pro',
    ctaLink: '/product/nova-pro-wireless-headphones',
    isActive: true,
    order: 1,
  },
  {
    id: 'banner-2',
    title: 'Kinetic Ergonomics & Speed',
    subtitle: 'Apex Aero Knit Runner 2026',
    badge: 'FLASH SALE • 25% OFF',
    description: 'Engineered carbon-plate propulsion with breathable dual-zone knit weave for all-day comfort.',
    price: 189,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1600&q=85',
    ctaText: 'Shop Footwear',
    ctaLink: '/product/apex-aero-knit-runner',
    isActive: true,
    order: 2,
  },
  {
    id: 'banner-3',
    title: 'Tactile Perfection For Creators',
    subtitle: 'Lumix Mechanical Master 75%',
    badge: 'LIMITED EDITION',
    description: 'Gasket-mounted acoustic dampening with hot-swappable lubricated switches and CNC aluminum chassis.',
    price: 159,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1600&q=85',
    ctaText: 'Discover Lumix',
    ctaLink: '/product/lumix-tactile-keyboard-75',
    isActive: true,
    order: 3,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-headphones-1',
    name: 'Nova Pro Active Noise-Cancelling Headphones',
    slug: 'nova-pro-wireless-headphones',
    brand: 'Novasound',
    categoryId: 'cat-electronics',
    categoryName: 'Electronics & Audio',
    basePrice: 349,
    originalPrice: 399,
    discount: 13,
    stock: 42,
    sku: 'NOV-AUD-01',
    shortDescription: 'Flagship audiophile wireless headphones featuring hybrid active noise cancellation and spatial soundstage.',
    description: 'Engineered for discerning listeners and studio professionals alike, the Nova Pro Wireless combines 40mm custom planar drivers with bespoke memory foam cushions. Seamless multi-device pairing and crystal-clear beamforming microphone arrays ensure peak performance whether mastering audio or taking boardroom calls.',
    features: [
      'Hybrid 4-microphone Active Noise Cancellation (-42dB attenuation)',
      'High-Resolution LDAC and aptX Adaptive wireless codec support',
      'Up to 52 hours of continuous playback with quick charge (15 mins = 6 hours)',
      'Ergonomic aerospace-grade aluminum yoke with soft protein leather headband',
    ],
    specifications: {
      'Driver Size': '40mm Titanium Biomembrane',
      'Frequency Response': '10Hz - 45,000Hz',
      'Bluetooth Version': 'Bluetooth 5.4 Low Energy',
      'Battery Life': '52 Hours (ANC off) / 40 Hours (ANC on)',
      'Weight': '254 grams',
    },
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=85',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=1200&q=85',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-hp-black',
        productId: 'prod-headphones-1',
        sku: 'NOV-AUD-01-BLK',
        colorName: 'Space Black',
        colorHex: '#1E1E24',
        price: 349,
        stock: 24,
        lowStockThreshold: 5,
        images: [
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=85',
          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=1200&q=85',
        ],
      },
      {
        id: 'var-hp-silver',
        productId: 'prod-headphones-1',
        sku: 'NOV-AUD-01-SLV',
        colorName: 'Platinum Silver',
        colorHex: '#D1D5DB',
        price: 349,
        stock: 14,
        lowStockThreshold: 4,
        images: [
          'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200&q=85',
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=85',
        ],
      },
      {
        id: 'var-hp-navy',
        productId: 'prod-headphones-1',
        sku: 'NOV-AUD-01-NVY',
        colorName: 'Midnight Navy',
        colorHex: '#1E293B',
        price: 359,
        stock: 4,
        lowStockThreshold: 5,
        images: [
          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=1200&q=85',
          'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200&q=85',
        ],
      },
    ],
    tags: ['Audio', 'ANC', 'Wireless', 'Flagship', 'Bluetooth 5.4'],
    rating: 4.9,
    reviewCount: 48,
    salesCount: 142,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isPublished: true,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-keyboard-1',
    name: 'Lumix Mechanical Master 75% Keyboard',
    slug: 'lumix-tactile-keyboard-75',
    brand: 'Lumix Labs',
    categoryId: 'cat-gaming',
    categoryName: 'Gaming & Workstation',
    basePrice: 159,
    originalPrice: 199,
    discount: 20,
    stock: 28,
    sku: 'LMX-KB-75',
    shortDescription: 'Gasket-mounted hot-swappable custom mechanical keyboard with precision rotary encoder and CNC chassis.',
    description: 'Experience deep, creamy acoustic feedback crafted through 5 layers of sound-dampening IXPE and poron foam. Equipped with pre-lubricated factory switches and South-facing RGB illumination.',
    features: [
      'Hot-swappable 5-pin PCB compatible with all Cherry-style switches',
      'Tri-mode connectivity: 2.4GHz Ultra-Low Latency, Bluetooth 5.2, USB-C',
      '4000mAh high-density battery providing 3 weeks of RGB-off typing',
      'Programmable tactile brass volume dial and QMK/VIA support',
    ],
    specifications: {
      'Layout': '75% Compact (82 Keys)',
      'Mounting Style': 'Gasket Dampened',
      'Switch Type': 'Pre-lubricated Tactile Marble 45g',
      'Keycaps': 'Double-shot PBT Cherry Profile',
      'Weight': '980g',
    },
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1200&q=85',
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-kb-white',
        productId: 'prod-keyboard-1',
        sku: 'LMX-KB-75-WHT',
        colorName: 'Chalk White',
        colorHex: '#F8FAFC',
        price: 159,
        stock: 16,
        lowStockThreshold: 4,
        images: [
          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1200&q=85',
        ],
      },
      {
        id: 'var-kb-black',
        productId: 'prod-keyboard-1',
        sku: 'LMX-KB-75-BLK',
        colorName: 'Basalt Black',
        colorHex: '#0F172A',
        price: 159,
        stock: 12,
        lowStockThreshold: 3,
        images: [
          'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=1200&q=85',
        ],
      },
    ],
    tags: ['Mechanical', 'Gasket Mount', 'Gaming', 'Desk Setup', 'RGB'],
    rating: 4.8,
    reviewCount: 36,
    salesCount: 98,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isPublished: true,
    createdAt: '2026-08-05T12:00:00Z',
  },
  {
    id: 'prod-shoes-1',
    name: 'Apex Aero Knit Velocity Runner',
    slug: 'apex-aero-knit-runner',
    brand: 'Aero Athletics',
    categoryId: 'cat-footwear',
    categoryName: 'Footwear & Sneakers',
    basePrice: 189,
    originalPrice: 240,
    discount: 21,
    stock: 65,
    sku: 'AERO-RUN-01',
    shortDescription: 'Featherlight marathon performance running sneaker with dual-density energy rebound foam.',
    description: 'Designed for runners seeking velocity without sacrificing joint cushioning. Features an integrated carbon-fiber propulsion shank and breathable dynamic mesh that molds to your instep.',
    features: [
      'Full-length embedded composite carbon propulsion plate',
      'Aerogel micro-cushioning heel cup with 85% energy return',
      'Continental-grade anti-slip rubber traction outsole',
      'Engineered one-piece recycled jacquard knit upper',
    ],
    specifications: {
      'Drop': '8mm Heel-to-Toe',
      'Weight': '210g (Size 9)',
      'Terrain': 'Road, Track, Treadmill',
      'Arch Support': 'Neutral to Medium',
    },
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&q=85',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-shoes-red',
        productId: 'prod-shoes-1',
        sku: 'AERO-RUN-RED-9',
        colorName: 'Crimson Volt',
        colorHex: '#DC2626',
        size: 'US 9',
        price: 189,
        stock: 22,
        lowStockThreshold: 5,
        images: [
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&q=85',
        ],
      },
      {
        id: 'var-shoes-black',
        productId: 'prod-shoes-1',
        sku: 'AERO-RUN-BLK-10',
        colorName: 'Stealth Onyx',
        colorHex: '#18181B',
        size: 'US 10',
        price: 189,
        stock: 28,
        lowStockThreshold: 6,
        images: [
          'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=1200&q=85',
        ],
      },
      {
        id: 'var-shoes-white',
        productId: 'prod-shoes-1',
        sku: 'AERO-RUN-WHT-95',
        colorName: 'Pure Glacier',
        colorHex: '#F1F5F9',
        size: 'US 9.5',
        price: 195,
        stock: 15,
        lowStockThreshold: 4,
        images: [
          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1200&q=85',
        ],
      },
    ],
    tags: ['Running', 'Carbon Plate', 'Sneakers', 'Marathon', 'Athletics'],
    rating: 4.9,
    reviewCount: 52,
    salesCount: 165,
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isPublished: true,
    createdAt: '2026-08-10T14:30:00Z',
  },
  {
    id: 'prod-watch-1',
    name: 'Vanguard Chronograph Minimalist Watch',
    slug: 'vanguard-chronograph-watch',
    brand: 'Horology Atelier',
    categoryId: 'cat-accessories',
    categoryName: 'Watches & Accessories',
    basePrice: 289,
    originalPrice: 350,
    discount: 17,
    stock: 18,
    sku: 'HRO-VAN-40',
    shortDescription: 'Hand-assembled sapphire crystal chronograph with surgical 316L steel case and Italian calfskin leather.',
    description: 'A masterclass in modern horology. The Vanguard features a sunburst dial, subtle 24-hour sub-dials, date aperture, and high-precision Japanese meca-quartz movement with mechanical sweep seconds.',
    features: [
      'Anti-reflective scratch-resistant double-domed sapphire crystal',
      '5 ATM (50 meters) water resistance',
      'Hand-stitched full-grain Italian vegetable tanned leather strap',
      'Luminescent Swiss Super-LumiNova hour hands and markers',
    ],
    specifications: {
      'Case Diameter': '40mm',
      'Case Thickness': '10.5mm',
      'Lug Width': '20mm',
      'Movement': 'Seiko VK64 Meca-Quartz Chronograph',
    },
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&q=85',
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-watch-silver',
        productId: 'prod-watch-1',
        sku: 'HRO-VAN-SLV-BRN',
        colorName: 'Silver & Cognac',
        colorHex: '#94A3B8',
        price: 289,
        stock: 10,
        lowStockThreshold: 3,
        images: [
          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&q=85',
        ],
      },
      {
        id: 'var-watch-black',
        productId: 'prod-watch-1',
        sku: 'HRO-VAN-BLK-BLK',
        colorName: 'Matte Gunmetal',
        colorHex: '#334155',
        price: 299,
        stock: 8,
        lowStockThreshold: 2,
        images: [
          'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=1200&q=85',
        ],
      },
    ],
    tags: ['Luxury', 'Watch', 'Chronograph', 'Sapphire', 'Horology'],
    rating: 4.7,
    reviewCount: 29,
    salesCount: 74,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isPublished: true,
    createdAt: '2026-08-12T09:15:00Z',
  },
  {
    id: 'prod-bag-1',
    name: 'Atelier Sovereign Leather Briefcase',
    slug: 'atelier-sovereign-leather-briefcase',
    brand: 'Atelier Maison',
    categoryId: 'cat-fashion',
    categoryName: 'Luxury & Apparel',
    basePrice: 420,
    originalPrice: 490,
    discount: 14,
    stock: 12,
    sku: 'ATL-SOV-BAG',
    shortDescription: 'Full-grain Tuscan bridle leather briefcase with padded 16-inch laptop compartment and brass hardware.',
    description: 'Meticulously crafted for the modern executive. Built to age gracefully into a rich personal patina, featuring reinforced stress rivets, detachable shoulder strap, and internal organizer for documents, stylus, and tech gear.',
    features: [
      'Certified vegetable-tanned 2.2mm full-grain leather',
      'Dedicated plush micro-suede 16" laptop sleeve',
      'Solid forged antique brass YKK Excella zippers',
      'Luggage trolley pass-through sleeve on reverse side',
    ],
    specifications: {
      'Dimensions': '41cm x 30cm x 9cm',
      'Capacity': '12 Liters',
      'Weight': '1.35 kg',
      'Hardware': 'Solid Brass with PVD coating',
    },
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1200&q=85',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-bag-tan',
        productId: 'prod-bag-1',
        sku: 'ATL-SOV-TAN',
        colorName: 'Caramel Tan',
        colorHex: '#92400E',
        price: 420,
        stock: 7,
        lowStockThreshold: 2,
        images: [
          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1200&q=85',
        ],
      },
      {
        id: 'var-bag-black',
        productId: 'prod-bag-1',
        sku: 'ATL-SOV-BLK',
        colorName: 'Midnight Noir',
        colorHex: '#09090B',
        price: 435,
        stock: 5,
        lowStockThreshold: 2,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1200&q=85',
        ],
      },
    ],
    tags: ['Leather', 'Briefcase', 'Executive', 'Luxury', 'Travel'],
    rating: 5.0,
    reviewCount: 19,
    salesCount: 41,
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    isPublished: true,
    createdAt: '2026-08-15T16:00:00Z',
  },
  {
    id: 'prod-phone-1',
    name: 'Zenith Pro 16 5G Titanium Edition',
    slug: 'zenith-pro-16-smartphone',
    brand: 'Zenith Mobile',
    categoryId: 'cat-electronics',
    categoryName: 'Electronics & Audio',
    basePrice: 999,
    originalPrice: 1199,
    discount: 16,
    stock: 35,
    sku: 'ZEN-16P-TI',
    shortDescription: 'Grade 5 titanium aerospace frame, 120Hz LTPO OLED display, and 200MP periscope optics.',
    description: 'The pinnacle of mobile engineering. Powered by an ultra-efficient 3nm neural engine, all-day silicon-carbon battery, and cinematic color science tuned by legendary cinematographers.',
    features: [
      '6.7-inch Super AMOLED LTPO 1-120Hz dynamic refresh display (3000 nits peak)',
      'Triple camera system: 200MP Main + 50MP Ultra-wide + 50MP 5x Optical Periscope',
      '5,400mAh dual-cell battery with 100W Wired and 50W Wireless Fast Charging',
      'IP68 Submersible Water and Dust Resistance',
    ],
    specifications: {
      'Processor': 'Neural Octa-Core 3.4GHz (3nm)',
      'RAM': '12GB / 16GB LPDDR5X',
      'Display': '6.7" 3120x1440 516 ppi',
      'Weight': '204g',
    },
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&q=85',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-phone-gray',
        productId: 'prod-phone-1',
        sku: 'ZEN-16P-256-GRY',
        colorName: 'Natural Titanium',
        colorHex: '#71717A',
        storage: '256 GB',
        price: 999,
        stock: 18,
        lowStockThreshold: 4,
        images: [
          'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&q=85',
        ],
      },
      {
        id: 'var-phone-blue',
        productId: 'prod-phone-1',
        sku: 'ZEN-16P-512-BLU',
        colorName: 'Deep Cobalt',
        colorHex: '#1E3A8A',
        storage: '512 GB',
        price: 1149,
        stock: 17,
        lowStockThreshold: 3,
        images: [
          'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1200&q=85',
        ],
      },
    ],
    tags: ['Smartphone', '5G', 'Titanium', 'OLED', 'Camera'],
    rating: 4.9,
    reviewCount: 88,
    salesCount: 230,
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isPublished: true,
    createdAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'prod-fan-1',
    name: 'AeroBreeze Silent Vortex Table Fan',
    slug: 'aerobreeze-silent-vortex-table-fan',
    brand: 'AeroHome Living',
    categoryId: 'cat-home',
    categoryName: 'Smart Living & Climate',
    basePrice: 89,
    originalPrice: 119,
    discount: 25,
    stock: 45,
    sku: 'AERO-FAN-01',
    shortDescription: 'Whisper-quiet DC motor desk circulator with 3D multidirectional oscillation and magnetic remote.',
    description: 'Engineered with aerodynamic bionic turbine blades that propel a concentrated column of cooling air up to 18 meters while emitting less than 21dB of acoustic murmur.',
    features: [
      'Ultra-efficient brushless DC motor with 12 micro-speed settings',
      'Dual oscillation: 90° horizontal and 85° vertical tilt',
      'Magnetic docking remote control and ambient sleep timer',
      'Energy efficient 18W power draw at maximum airflow',
    ],
    specifications: {
      'Airflow Distance': 'Up to 18 meters',
      'Noise Level': '21dB - 48dB',
      'Power Consumption': '18 Watts Max',
      'Cord Length': '2.0 meters',
    },
    images: [
      'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-fan-white',
        productId: 'prod-fan-1',
        sku: 'AERO-FAN-WHT',
        colorName: 'Nordic White',
        colorHex: '#F8FAFC',
        price: 89,
        stock: 30,
        lowStockThreshold: 5,
        images: [
          'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=1200&q=85',
        ],
      },
      {
        id: 'var-fan-slate',
        productId: 'prod-fan-1',
        sku: 'AERO-FAN-SLT',
        colorName: 'Slate Charcoal',
        colorHex: '#334155',
        price: 94,
        stock: 15,
        lowStockThreshold: 4,
        images: [
          'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=1200&q=85',
        ],
      },
    ],
    tags: ['Appliances', 'Fan', 'Vortex', 'Silent DC', 'Summer'],
    rating: 4.8,
    reviewCount: 31,
    salesCount: 89,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isPublished: true,
    createdAt: '2026-08-22T08:00:00Z',
  },
  {
    id: 'prod-mouse-1',
    name: 'Viper Wireless 8K Ultra-Light Gaming Mouse',
    slug: 'viper-wireless-8k-gaming-mouse',
    brand: 'Lumix Labs',
    categoryId: 'cat-gaming',
    categoryName: 'Gaming & Workstation',
    basePrice: 129,
    originalPrice: 159,
    discount: 18,
    stock: 50,
    sku: 'LMX-VIP-8K',
    shortDescription: '49-gram magnesium alloy chassis with genuine 8000Hz polling rate and 30,000 DPI optical sensor.',
    description: 'Built for esports champions. Eliminates every fraction of a millisecond of latency with optical microswitches rated for 90 million clicks and zero-drag pure virgin PTFE skates.',
    features: [
      'Sub-50g featherlight skeleton alloy shell',
      'True 8000Hz hyper-polling wireless dongle included',
      'Optical switch actuation (0.2ms latency, zero debounce delay)',
      'Up to 80 hours battery on 1000Hz / 24 hours on 8000Hz',
    ],
    specifications: {
      'Sensor': 'PAW3395 30K Optical Sensor',
      'Max Acceleration': '50G',
      'Tracking Speed': '650 IPS',
      'Weight': '49 grams',
    },
    images: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=1200&q=85',
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-mouse-black',
        productId: 'prod-mouse-1',
        sku: 'LMX-VIP-BLK',
        colorName: 'Shadow Black',
        colorHex: '#18181B',
        price: 129,
        stock: 32,
        lowStockThreshold: 5,
        images: [
          'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=1200&q=85',
        ],
      },
      {
        id: 'var-mouse-white',
        productId: 'prod-mouse-1',
        sku: 'LMX-VIP-WHT',
        colorName: 'Ghost White',
        colorHex: '#F8FAFC',
        price: 129,
        stock: 18,
        lowStockThreshold: 4,
        images: [
          'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=1200&q=85',
        ],
      },
    ],
    tags: ['Gaming', 'Mouse', '8KHz', 'Esports', 'Ultralight'],
    rating: 4.9,
    reviewCount: 44,
    salesCount: 112,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isPublished: true,
    createdAt: '2026-08-25T15:00:00Z',
  },
  {
    id: 'prod-jacket-1',
    name: 'Nordic Technical Wool Trench Coat',
    slug: 'nordic-technical-wool-trench-coat',
    brand: 'Atelier Maison',
    categoryId: 'cat-fashion',
    categoryName: 'Luxury & Apparel',
    basePrice: 380,
    originalPrice: 450,
    discount: 15,
    stock: 22,
    sku: 'ATL-TRENCH-01',
    shortDescription: 'Water-repellent double-faced Merino wool trench coat with magnetic collar closure and silk lining.',
    description: 'The epitome of architectural winter fashion. Woven from superfine 18.5-micron Australian merino wool treated with a non-toxic fluorocarbon-free hydrophobic finish.',
    features: [
      '100% Superfine Australian Merino wool shell (650 gsm)',
      'Water and wind resistant breathable membrane',
      'Concealed horn buttons and storm welt pockets',
      'Tailored articulated sleeves for seamless range of motion',
    ],
    specifications: {
      'Material': '100% Merino Wool, 100% Cupro Lining',
      'Care': 'Specialist Dry Clean Only',
      'Fit': 'Contemporary Tailored Relaxed',
      'Length': 'Mid-calf (112cm)',
    },
    images: [
      'https://images.unsplash.com/photo-1539533018447-63fcce667883?w=1200&q=85',
      'https://images.unsplash.com/photo-1544441893-675973e31985?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-coat-camel',
        productId: 'prod-jacket-1',
        sku: 'ATL-TRN-CML-M',
        colorName: 'Heritage Camel',
        colorHex: '#B45309',
        size: 'Medium',
        price: 380,
        stock: 12,
        lowStockThreshold: 3,
        images: [
          'https://images.unsplash.com/photo-1539533018447-63fcce667883?w=1200&q=85',
        ],
      },
      {
        id: 'var-coat-charcoal',
        productId: 'prod-jacket-1',
        sku: 'ATL-TRN-CHR-L',
        colorName: 'Charcoal Mélange',
        colorHex: '#374151',
        size: 'Large',
        price: 380,
        stock: 10,
        lowStockThreshold: 3,
        images: [
          'https://images.unsplash.com/photo-1544441893-675973e31985?w=1200&q=85',
        ],
      },
    ],
    tags: ['Apparel', 'Wool', 'Coat', 'Winter', 'Luxury'],
    rating: 4.8,
    reviewCount: 22,
    salesCount: 56,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isPublished: true,
    createdAt: '2026-08-28T18:00:00Z',
  },
  {
    id: 'prod-speaker-1',
    name: 'Aura High-Fidelity Smart Ambient Speaker',
    slug: 'aura-smart-ambient-speaker',
    brand: 'Novasound',
    categoryId: 'cat-smart-devices',
    categoryName: 'Smart Devices & IoT',
    basePrice: 249,
    originalPrice: 299,
    discount: 16,
    stock: 25,
    sku: 'NOV-AURA-01',
    shortDescription: 'Omnidirectional 360° acoustic sound with glass ambient lighting and AirPlay 2 / Spotify Connect.',
    description: 'Fills any architectural room with warm, spatial acoustics. Hand-blown acoustic glass resonance chamber with adjustable rhythmic twilight illumination.',
    features: [
      '360-degree omnidirectional acoustic diffusion wave',
      'True lossless Wi-Fi streaming via AirPlay 2, Tidal Connect & Spotify Connect',
      'Integrated tactile brass touch rings and glass dimming dial',
      'Room-calibrating DSP algorithm that analyzes room reflections in real time',
    ],
    specifications: {
      'Amplifier Power': '65W Class-D Tri-Amp',
      'Connectivity': 'Wi-Fi 6, Bluetooth 5.3, Optical 3.5mm Aux',
      'Dimensions': '190mm x 260mm',
      'Weight': '2.6 kg',
    },
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-speaker-clear',
        productId: 'prod-speaker-1',
        sku: 'NOV-AURA-CLR',
        colorName: 'Crystal Clear',
        colorHex: '#E2E8F0',
        price: 249,
        stock: 15,
        lowStockThreshold: 4,
        images: [
          'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1200&q=85',
        ],
      },
      {
        id: 'var-speaker-smoke',
        productId: 'prod-speaker-1',
        sku: 'NOV-AURA-SMK',
        colorName: 'Smoked Obsidian',
        colorHex: '#1E293B',
        price: 259,
        stock: 10,
        lowStockThreshold: 3,
        images: [
          'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1200&q=85',
        ],
      },
    ],
    tags: ['Smart Speaker', 'HiFi', 'AirPlay', 'Lighting', 'Audio'],
    rating: 4.9,
    reviewCount: 38,
    salesCount: 82,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isPublished: true,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'prod-skincare-1',
    name: 'Botanical Radiance Cellular Recovery Serum',
    slug: 'botanical-radiance-cellular-serum',
    brand: 'Flora Botanica',
    categoryId: 'cat-beauty',
    categoryName: 'Grooming & Skincare',
    basePrice: 78,
    originalPrice: 95,
    discount: 17,
    stock: 60,
    sku: 'FLR-SERUM-50',
    shortDescription: 'Bio-fermented peptide serum with concentrated niacinamide and botanical squalane for deep cellular renewal.',
    description: 'Dermatologist tested and clinical grade. Enhances collagen synthesis and barrier resilience while diminishing fine lines and environmental hyperpigmentation.',
    features: [
      '10% Quad-Peptide Complex with Multi-molecular Hyaluronic Acid',
      '100% vegan, cruelty-free, fragrance-free, non-comedogenic',
      'Amber UV-protected pharmaceutical glass bottle with precision dropper',
      'Clinically shown to boost hydration by 142% within 2 hours',
    ],
    specifications: {
      'Volume': '50ml / 1.7 fl oz',
      'Skin Type': 'All skin types, sensitive safe',
      'Application': 'Morning and Night after cleansing',
      'Formulation': 'Lightweight silky watery essence',
    },
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=1200&q=85',
      'https://images.unsplash.com/photo-1608248597359-5561a0f8bfb2?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-serum-50',
        productId: 'prod-skincare-1',
        sku: 'FLR-SERUM-50ML',
        colorName: 'Standard Bottle',
        colorHex: '#D97706',
        storage: '50 ml',
        price: 78,
        stock: 40,
        lowStockThreshold: 8,
        images: [
          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=1200&q=85',
        ],
      },
      {
        id: 'var-serum-100',
        productId: 'prod-skincare-1',
        sku: 'FLR-SERUM-100ML',
        colorName: 'Value Duo Size',
        colorHex: '#B45309',
        storage: '100 ml',
        price: 128,
        stock: 20,
        lowStockThreshold: 5,
        images: [
          'https://images.unsplash.com/photo-1608248597359-5561a0f8bfb2?w=1200&q=85',
        ],
      },
    ],
    tags: ['Skincare', 'Serum', 'Peptides', 'Anti-Aging', 'Clean Beauty'],
    rating: 4.9,
    reviewCount: 57,
    salesCount: 175,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isPublished: true,
    createdAt: '2026-09-03T11:20:00Z',
  },
  {
    id: 'prod-controller-1',
    name: 'Vortex Elite Wireless Pro Controller',
    slug: 'vortex-elite-pro-controller',
    brand: 'Lumix Labs',
    categoryId: 'cat-gaming',
    categoryName: 'Gaming & Workstation',
    basePrice: 169,
    originalPrice: 199,
    discount: 15,
    stock: 30,
    sku: 'LMX-CTRL-01',
    shortDescription: 'Hall-effect magnetic thumbsticks with anti-drift guarantee, interchangeable paddles, and tactile triggers.',
    description: 'Precision engineered for competitive supremacy. Features contactless hall-effect electromagnetic joysticks that never develop stick drift, instant hair-trigger locks, and textured rubberized grips.',
    features: [
      'Hall Effect sensor joysticks and triggers with zero deadzone drift',
      '4 customizable rear ergonomic aluminum paddles',
      'Adjustable 3-way hair trigger locks for instant rapid-fire response',
      'Compatible with PC, Mac, iOS, Android, and consoles',
    ],
    specifications: {
      'Connectivity': '2.4GHz Dongle, Bluetooth 5.3, USB-C 1000Hz polling',
      'Battery': '1200mAh Lithium Ion (30+ hours per charge)',
      'Weight': '280 grams',
    },
    images: [
      'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=1200&q=85',
    ],
    variants: [
      {
        id: 'var-ctrl-white',
        productId: 'prod-controller-1',
        sku: 'LMX-CTRL-WHT',
        colorName: 'Arctic Frost',
        colorHex: '#E2E8F0',
        price: 169,
        stock: 18,
        lowStockThreshold: 4,
        images: [
          'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=1200&q=85',
        ],
      },
      {
        id: 'var-ctrl-black',
        productId: 'prod-controller-1',
        sku: 'LMX-CTRL-BLK',
        colorName: 'Midnight Stealth',
        colorHex: '#0F172A',
        price: 169,
        stock: 12,
        lowStockThreshold: 3,
        images: [
          'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=1200&q=85',
        ],
      },
    ],
    tags: ['Gaming', 'Controller', 'Hall Effect', 'Esports', 'PC Gaming'],
    rating: 4.8,
    reviewCount: 26,
    salesCount: 68,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isPublished: true,
    createdAt: '2026-09-05T13:40:00Z',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-save10',
    code: 'SAVE10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 50,
    maxDiscount: 50,
    expiryDate: '2027-12-31T23:59:59Z',
    usageLimit: 1000,
    usedCount: 142,
    isActive: true,
  },
  {
    id: 'coup-novavip',
    code: 'NOVAVIP',
    discountType: 'FIXED',
    discountValue: 40,
    minOrderValue: 200,
    expiryDate: '2027-12-31T23:59:59Z',
    usageLimit: 500,
    usedCount: 78,
    isActive: true,
  },
  {
    id: 'coup-welcome20',
    code: 'WELCOME20',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minOrderValue: 100,
    maxDiscount: 60,
    expiryDate: '2027-12-31T23:59:59Z',
    usageLimit: 2000,
    usedCount: 310,
    isActive: true,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-headphones-1',
    customerName: 'Marcus Vance',
    customerAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&q=80',
    rating: 5,
    title: 'Unbelievable acoustic soundstage and ANC',
    comment: 'The instrument separation on these headphones rivals open-back planar monitors, but with stellar noise cancellation. Build quality feels every bit as premium as an Apple or B&O device. Battery life is astounding.',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80'],
    isVerifiedPurchase: true,
    isApproved: true,
    createdAt: '2026-08-20T14:22:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-headphones-1',
    customerName: 'Elena Rostova',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80',
    rating: 5,
    title: 'Pure perfection for frequent flights',
    comment: 'Cuts out cabin engine rumble effortlessly. The memory foam earcups never put uncomfortable pressure on my glasses. 10/10 recommendation.',
    images: [],
    isVerifiedPurchase: true,
    isApproved: true,
    createdAt: '2026-08-24T18:10:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-keyboard-1',
    customerName: 'David Chen',
    customerAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&q=80',
    rating: 5,
    title: 'The acoustic "thock" sound right out of the box',
    comment: 'No modding needed whatsoever. Factory lubed switches are buttery smooth and the solid aluminum chassis weighs nearly a full kilogram. The volume knob is super crisp.',
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&q=80'],
    isVerifiedPurchase: true,
    isApproved: true,
    createdAt: '2026-08-28T09:45:00Z',
  },
  {
    id: 'rev-4',
    productId: 'prod-shoes-1',
    customerName: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&q=80',
    rating: 5,
    title: 'Shaved 45 seconds off my 10K split',
    comment: 'The carbon propulsion is noticeable from the first stride. Snug midfoot lockdown with plenty of room in the toe box. Plus the crimson volt colorway looks killer in person.',
    images: [],
    isVerifiedPurchase: true,
    isApproved: true,
    createdAt: '2026-09-02T16:30:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'NC-2026-8901',
    userId: 'usr-customer-1',
    customerName: 'Alexander Hayes',
    customerEmail: 'alex.hayes@example.com',
    customerPhone: '+1 (555) 234-5678',
    shippingAddress: {
      fullName: 'Alexander Hayes',
      phone: '+1 (555) 234-5678',
      street: '742 Evergreen Terrace, Suite 4B',
      city: 'Seattle',
      area: 'Downtown',
      postalCode: '98101',
    },
    deliveryNote: 'Please leave at the front reception if unattended.',
    items: [
      {
        id: 'item-101',
        productId: 'prod-headphones-1',
        productName: 'Nova Pro Active Noise-Cancelling Headphones',
        productSlug: 'nova-pro-wireless-headphones',
        productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
        variantId: 'var-hp-black',
        variantSku: 'NOV-AUD-01-BLK',
        variantColor: 'Space Black',
        price: 349,
        quantity: 1,
        total: 349,
      },
      {
        id: 'item-102',
        productId: 'prod-mouse-1',
        productName: 'Viper Wireless 8K Ultra-Light Gaming Mouse',
        productSlug: 'viper-wireless-8k-gaming-mouse',
        productImage: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&q=80',
        variantId: 'var-mouse-black',
        variantSku: 'LMX-VIP-BLK',
        variantColor: 'Shadow Black',
        price: 129,
        quantity: 1,
        total: 129,
      },
    ],
    subtotal: 478,
    discount: 47.8,
    couponCode: 'SAVE10',
    shippingFee: 0,
    tax: 34.42,
    total: 464.62,
    paymentMethod: 'CARD',
    paymentStatus: 'PAID',
    orderStatus: 'DELIVERED',
    trackingNumber: 'NV-98234176-US',
    timeline: [
      {
        status: 'PENDING',
        title: 'Order Placed',
        timestamp: '2026-08-28T10:14:00Z',
        note: 'Payment authorized via Visa ending in 4242.',
      },
      {
        status: 'CONFIRMED',
        title: 'Order Verified',
        timestamp: '2026-08-28T10:30:00Z',
        note: 'Inventory allocated and packed at Central Distribution Hub.',
      },
      {
        status: 'SHIPPED',
        title: 'Dispatched with Courier',
        timestamp: '2026-08-29T08:00:00Z',
        note: 'Handed over to FedEx Priority Express.',
      },
      {
        status: 'DELIVERED',
        title: 'Package Delivered',
        timestamp: '2026-08-30T14:45:00Z',
        note: 'Signed by recipient: A. Hayes.',
      },
    ],
    createdAt: '2026-08-28T10:14:00Z',
  },
  {
    id: 'ord-1002',
    orderNumber: 'NC-2026-8902',
    userId: 'usr-customer-2',
    customerName: 'Sophia Lin',
    customerEmail: 'sophia.lin@example.com',
    customerPhone: '+1 (555) 876-5432',
    shippingAddress: {
      fullName: 'Sophia Lin',
      phone: '+1 (555) 876-5432',
      street: '1200 Grand Avenue, Apt 18E',
      city: 'San Francisco',
      area: 'South of Market',
      postalCode: '94103',
    },
    items: [
      {
        id: 'item-103',
        productId: 'prod-shoes-1',
        productName: 'Apex Aero Knit Velocity Runner',
        productSlug: 'apex-aero-knit-runner',
        productImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
        variantId: 'var-shoes-red',
        variantSku: 'AERO-RUN-RED-9',
        variantColor: 'Crimson Volt',
        variantSize: 'US 9',
        price: 189,
        quantity: 1,
        total: 189,
      },
    ],
    subtotal: 189,
    discount: 0,
    shippingFee: 0,
    tax: 15.12,
    total: 204.12,
    paymentMethod: 'CARD',
    paymentStatus: 'PAID',
    orderStatus: 'SHIPPED',
    trackingNumber: 'NV-48190234-US',
    timeline: [
      {
        status: 'PENDING',
        title: 'Order Placed',
        timestamp: '2026-09-10T11:00:00Z',
        note: 'Payment processed successfully.',
      },
      {
        status: 'CONFIRMED',
        title: 'Order Confirmed',
        timestamp: '2026-09-10T12:00:00Z',
        note: 'Order prepared for shipping.',
      },
      {
        status: 'SHIPPED',
        title: 'In Transit',
        timestamp: '2026-09-11T09:30:00Z',
        note: 'In transit to Northern California sorting facility.',
      },
    ],
    createdAt: '2026-09-10T11:00:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Novacart Executive Admin',
    email: 'admin@novacart.com',
    password: 'admin123',
    role: 'ADMIN',
    phone: '+1 (555) 000-1111',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&q=80',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'usr-customer-1',
    name: 'Alexander Hayes',
    email: 'alex.hayes@example.com',
    password: 'customer123',
    role: 'CUSTOMER',
    phone: '+1 (555) 234-5678',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&q=80',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr-customer-2',
    name: 'Sophia Lin',
    email: 'sophia.lin@example.com',
    password: 'customer123',
    role: 'CUSTOMER',
    phone: '+1 (555) 876-5432',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80',
    createdAt: '2026-08-15T12:00:00Z',
  },
];
